name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SONAR_SCANNER_VERSION: 4.4.0.2170

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    
    - name: Run tests and coverage
      run: npm test
    
    - name: Set Google Cloud Project
      run: gcloud config set project mspr-payetonkawa-95a92

    - name: Authenticate with Google Cloud
      run: gcloud auth activate-service-account --key-file=mspr-payetonkawa-key.json
    
    - name: Deploy to Google Cloud Platform
      if: ${{ success() }}
      run: |
        gcloud builds submit --tag gcr.io/mspr-payetonkawa-95a92/webshop
        gcloud run deploy mspr-payetonkawa-95a92-webshop --image gcr.io/mspr-payetonkawa-95a92/webshop --platform managed --region us-central1 --allow-unauthenticated
